var houseHoldData = [
  {
    State: "Alabama",
    "Female householder": 266817,
    "Male householder": 82057,
    "Married-couple family household": 906990,
    "Nonfamily household": 677286,
    "Total households Overall": 1933150,
    "Average Household Size - Female householder": 3.53,
    "Average Household Size - Male householder": 3.44,
    "Average Household Size - Married-couple family household": 3.15,
    "Average Household Size - Nonfamily household": 1.2,
    "Average Household Size - Overall": 2.53,
    "Households with one or more people under 18 years - Female householder": 0.614,
    "Households with one or more people under 18 years - Male householder": 0.544,
    "Households with one or more people under 18 years - Married-couple family household": 0.39,
    "Households with one or more people under 18 years - Nonfamily household": 0.007,
    "Households with one or more people under 18 years - Overall": 0.293,
    "Households with one or more people 60 years and over - Female householder": 0.315,
    "Households with one or more people 60 years and over - Male householder": 0.332,
    "Households with one or more people 60 years and over - Married-couple family household": 0.417,
    "Households with one or more people 60 years and over - Nonfamily household": 0.486,
    "Households with one or more people 60 years and over - Overall": 0.423,
  },
  {
    State: "Alaska",
    "Female householder": 26188,
    "Male householder": 15178,
    "Married-couple family household": 129605,
    "Nonfamily household": 93405,
    "Total households Overall": 264376,
    "Average Household Size - Female householder": 3.64,
    "Average Household Size - Male householder": 3.48,
    "Average Household Size - Married-couple family household": 3.35,
    "Average Household Size - Nonfamily household": 1.31,
    "Average Household Size - Overall": 2.67,
    "Households with one or more people under 18 years - Female householder": 0.693,
    "Households with one or more people under 18 years - Male householder": 0.608,
    "Households with one or more people under 18 years - Married-couple family household": 0.449,
    "Households with one or more people under 18 years - Nonfamily household": 0.01,
    "Households with one or more people under 18 years - Overall": 0.327,
    "Households with one or more people 60 years and over - Female householder": 0.262,
    "Households with one or more people 60 years and over - Male householder": 0.321,
    "Households with one or more people 60 years and over - Married-couple family household": 0.359,
    "Households with one or more people 60 years and over - Nonfamily household": 0.404,
    "Households with one or more people 60 years and over - Overall": 0.363,
  },
  {
    State: "Arizona",
    "Female householder": 330966,
    "Male householder": 157515,
    "Married-couple family household": 1291812,
    "Nonfamily household": 958843,
    "Total households Overall": 2739136,
    "Average Household Size - Female householder": 3.46,
    "Average Household Size - Male householder": 3.27,
    "Average Household Size - Married-couple family household": 3.18,
    "Average Household Size - Nonfamily household": 1.3,
    "Average Household Size - Overall": 2.56,
    "Households with one or more people under 18 years - Female householder": 0.627,
    "Households with one or more people under 18 years - Male householder": 0.583,
    "Households with one or more people under 18 years - Married-couple family household": 0.4,
    "Households with one or more people under 18 years - Nonfamily household": 0.009,
    "Households with one or more people under 18 years - Overall": 0.301,
    "Households with one or more people 60 years and over - Female householder": 0.303,
    "Households with one or more people 60 years and over - Male householder": 0.268,
    "Households with one or more people 60 years and over - Married-couple family household": 0.449,
    "Households with one or more people 60 years and over - Nonfamily household": 0.468,
    "Households with one or more people 60 years and over - Overall": 0.428,
  },
  {
    State: "Arkansas",
    "Female householder": 151520,
    "Male householder": 54958,
    "Married-couple family household": 556967,
    "Nonfamily household": 408249,
    "Total households Overall": 1171694,
    "Average Household Size - Female householder": 3.41,
    "Average Household Size - Male householder": 3.23,
    "Average Household Size - Married-couple family household": 3.13,
    "Average Household Size - Nonfamily household": 1.22,
    "Average Household Size - Overall": 2.51,
    "Households with one or more people under 18 years - Female householder": 0.66,
    "Households with one or more people under 18 years - Male householder": 0.572,
    "Households with one or more people under 18 years - Married-couple family household": 0.41,
    "Households with one or more people under 18 years - Nonfamily household": 0.009,
    "Households with one or more people under 18 years - Overall": 0.31,
    "Households with one or more people 60 years and over - Female householder": 0.282,
    "Households with one or more people 60 years and over - Male householder": 0.302,
    "Households with one or more people 60 years and over - Married-couple family household": 0.401,
    "Households with one or more people 60 years and over - Nonfamily household": 0.483,
    "Households with one or more people 60 years and over - Overall": 0.41,
  },
  {
    State: "California",
    "Female householder": 1717455,
    "Male householder": 830462,
    "Married-couple family household": 6545790,
    "Nonfamily household": 4222115,
    "Total households Overall": 13315822,
    "Average Household Size - Female householder": 3.7,
    "Average Household Size - Male householder": 3.59,
    "Average Household Size - Married-couple family household": 3.57,
    "Average Household Size - Nonfamily household": 1.37,
    "Average Household Size - Overall": 2.89,
    "Households with one or more people under 18 years - Female householder": 0.563,
    "Households with one or more people under 18 years - Male householder": 0.511,
    "Households with one or more people under 18 years - Married-couple family household": 0.46,
    "Households with one or more people under 18 years - Nonfamily household": 0.008,
    "Households with one or more people under 18 years - Overall": 0.333,
    "Households with one or more people 60 years and over - Female householder": 0.37,
    "Households with one or more people 60 years and over - Male householder": 0.362,
    "Households with one or more people 60 years and over - Married-couple family household": 0.402,
    "Households with one or more people 60 years and over - Nonfamily household": 0.442,
    "Households with one or more people 60 years and over - Overall": 0.408,
  },
  {
    State: "Colorado",
    "Female householder": 206077,
    "Male householder": 104109,
    "Married-couple family household": 1117627,
    "Nonfamily household": 850231,
    "Total households Overall": 2278044,
    "Average Household Size - Female householder": 3.32,
    "Average Household Size - Male householder": 3.13,
    "Average Household Size - Married-couple family household": 3.13,
    "Average Household Size - Nonfamily household": 1.35,
    "Average Household Size - Overall": 2.48,
    "Households with one or more people under 18 years - Female householder": 0.622,
    "Households with one or more people under 18 years - Male householder": 0.573,
    "Households with one or more people under 18 years - Married-couple family household": 0.428,
    "Households with one or more people under 18 years - Nonfamily household": 0.006,
    "Households with one or more people under 18 years - Overall": 0.294,
    "Households with one or more people 60 years and over - Female householder": 0.279,
    "Households with one or more people 60 years and over - Male householder": 0.254,
    "Households with one or more people 60 years and over - Married-couple family household": 0.367,
    "Households with one or more people 60 years and over - Nonfamily household": 0.386,
    "Households with one or more people 60 years and over - Overall": 0.361,
  },
  {
    State: "Connecticut",
    "Female householder": 176317,
    "Male householder": 67929,
    "Married-couple family household": 667622,
    "Nonfamily household": 497939,
    "Total households Overall": 1409807,
    "Average Household Size - Female householder": 3.22,
    "Average Household Size - Male householder": 3.12,
    "Average Household Size - Married-couple family household": 3.15,
    "Average Household Size - Nonfamily household": 1.24,
    "Average Household Size - Overall": 2.48,
    "Households with one or more people under 18 years - Female householder": 0.589,
    "Households with one or more people under 18 years - Male householder": 0.497,
    "Households with one or more people under 18 years - Married-couple family household": 0.404,
    "Households with one or more people under 18 years - Nonfamily household": 0.006,
    "Households with one or more people under 18 years - Overall": 0.291,
    "Households with one or more people 60 years and over - Female householder": 0.303,
    "Households with one or more people 60 years and over - Male householder": 0.337,
    "Households with one or more people 60 years and over - Married-couple family household": 0.43,
    "Households with one or more people 60 years and over - Nonfamily household": 0.491,
    "Households with one or more people 60 years and over - Overall": 0.431,
  },
  {
    State: "Delaware",
    "Female householder": 48439,
    "Male householder": 19749,
    "Married-couple family household": 184317,
    "Nonfamily household": 136495,
    "Total households Overall": 389000,
    "Average Household Size - Female householder": 3.54,
    "Average Household Size - Male householder": 3.25,
    "Average Household Size - Married-couple family household": 3.06,
    "Average Household Size - Nonfamily household": 1.26,
    "Average Household Size - Overall": 2.5,
    "Households with one or more people under 18 years - Female householder": 0.629,
    "Households with one or more people under 18 years - Male householder": 0.564,
    "Households with one or more people under 18 years - Married-couple family household": 0.349,
    "Households with one or more people under 18 years - Nonfamily household": 0.006,
    "Households with one or more people under 18 years - Overall": 0.275,
    "Households with one or more people 60 years and over - Female householder": 0.305,
    "Households with one or more people 60 years and over - Male householder": 0.285,
    "Households with one or more people 60 years and over - Married-couple family household": 0.484,
    "Households with one or more people 60 years and over - Nonfamily household": 0.513,
    "Households with one or more people 60 years and over - Overall": 0.462,
  },
  {
    State: "District of Columbia",
    "Female householder": 40342,
    "Male householder": 10227,
    "Married-couple family household": 79884,
    "Nonfamily household": 185332,
    "Total households Overall": 315785,
    "Average Household Size - Female householder": 3.5,
    "Average Household Size - Male householder": 2.65,
    "Average Household Size - Married-couple family household": 2.99,
    "Average Household Size - Nonfamily household": 1.27,
    "Average Household Size - Overall": 2.03,
    "Households with one or more people under 18 years - Female householder": 0.615,
    "Households with one or more people under 18 years - Male householder": 0.468,
    "Households with one or more people under 18 years - Married-couple family household": 0.402,
    "Households with one or more people under 18 years - Nonfamily household": 0.002,
    "Households with one or more people under 18 years - Overall": 0.196,
    "Households with one or more people 60 years and over - Female householder": 0.339,
    "Households with one or more people 60 years and over - Male householder": 0.337,
    "Households with one or more people 60 years and over - Married-couple family household": 0.291,
    "Households with one or more people 60 years and over - Nonfamily household": 0.266,
    "Households with one or more people 60 years and over - Overall": 0.284,
  },
  {
    State: "Florida",
    "Female householder": 1064138,
    "Male householder": 428971,
    "Married-couple family household": 3905043,
    "Nonfamily household": 2955289,
    "Total households Overall": 8353441,
    "Average Household Size - Female householder": 3.52,
    "Average Household Size - Male householder": 3.37,
    "Average Household Size - Married-couple family household": 3.12,
    "Average Household Size - Nonfamily household": 1.28,
    "Average Household Size - Overall": 2.53,
    "Households with one or more people under 18 years - Female householder": 0.571,
    "Households with one or more people under 18 years - Male householder": 0.508,
    "Households with one or more people under 18 years - Married-couple family household": 0.354,
    "Households with one or more people under 18 years - Nonfamily household": 0.007,
    "Households with one or more people under 18 years - Overall": 0.267,
    "Households with one or more people 60 years and over - Female householder": 0.35,
    "Households with one or more people 60 years and over - Male householder": 0.356,
    "Households with one or more people 60 years and over - Married-couple family household": 0.487,
    "Households with one or more people 60 years and over - Nonfamily household": 0.514,
    "Households with one or more people 60 years and over - Overall": 0.472,
  },
  {
    State: "Georgia",
    "Female householder": 590477,
    "Male householder": 189615,
    "Married-couple family household": 1848105,
    "Nonfamily household": 1318293,
    "Total households Overall": 3946490,
    "Average Household Size - Female householder": 3.53,
    "Average Household Size - Male householder": 3.42,
    "Average Household Size - Married-couple family household": 3.29,
    "Average Household Size - Nonfamily household": 1.26,
    "Average Household Size - Overall": 2.65,
    "Households with one or more people under 18 years - Female householder": 0.633,
    "Households with one or more people under 18 years - Male householder": 0.537,
    "Households with one or more people under 18 years - Married-couple family household": 0.43,
    "Households with one or more people under 18 years - Nonfamily household": 0.008,
    "Households with one or more people under 18 years - Overall": 0.324,
    "Households with one or more people 60 years and over - Female householder": 0.288,
    "Households with one or more people 60 years and over - Male householder": 0.305,
    "Households with one or more people 60 years and over - Married-couple family household": 0.382,
    "Households with one or more people 60 years and over - Nonfamily household": 0.417,
    "Households with one or more people 60 years and over - Overall": 0.376,
  },
  {
    State: "Hawaii",
    "Female householder": 61141,
    "Male householder": 27057,
    "Married-couple family household": 244407,
    "Nonfamily household": 151301,
    "Total households Overall": 483906,
    "Average Household Size - Female householder": 3.75,
    "Average Household Size - Male householder": 3.73,
    "Average Household Size - Married-couple family household": 3.6,
    "Average Household Size - Nonfamily household": 1.32,
    "Average Household Size - Overall": 2.92,
    "Households with one or more people under 18 years - Female householder": 0.537,
    "Households with one or more people under 18 years - Male householder": 0.503,
    "Households with one or more people under 18 years - Married-couple family household": 0.413,
    "Households with one or more people under 18 years - Nonfamily household": 0.008,
    "Households with one or more people under 18 years - Overall": 0.307,
    "Households with one or more people 60 years and over - Female householder": 0.509,
    "Households with one or more people 60 years and over - Male householder": 0.479,
    "Households with one or more people 60 years and over - Married-couple family household": 0.484,
    "Households with one or more people 60 years and over - Nonfamily household": 0.506,
    "Households with one or more people 60 years and over - Overall": 0.494,
  },
  {
    State: "Idaho",
    "Female householder": 58420,
    "Male householder": 31562,
    "Married-couple family household": 372111,
    "Nonfamily household": 213230,
    "Total households Overall": 675323,
    "Average Household Size - Female householder": 3.43,
    "Average Household Size - Male householder": 3.35,
    "Average Household Size - Married-couple family household": 3.26,
    "Average Household Size - Nonfamily household": 1.33,
    "Average Household Size - Overall": 2.67,
    "Households with one or more people under 18 years - Female householder": 0.641,
    "Households with one or more people under 18 years - Male householder": 0.634,
    "Households with one or more people under 18 years - Married-couple family household": 0.425,
    "Households with one or more people under 18 years - Nonfamily household": 0.008,
    "Households with one or more people under 18 years - Overall": 0.322,
    "Households with one or more people 60 years and over - Female householder": 0.283,
    "Households with one or more people 60 years and over - Male householder": 0.247,
    "Households with one or more people 60 years and over - Married-couple family household": 0.394,
    "Households with one or more people 60 years and over - Nonfamily household": 0.479,
    "Households with one or more people 60 years and over - Overall": 0.404,
  },
  {
    State: "Illinois",
    "Female householder": 596133,
    "Male householder": 236088,
    "Married-couple family household": 2301882,
    "Nonfamily household": 1834658,
    "Total households Overall": 4968761,
    "Average Household Size - Female householder": 3.36,
    "Average Household Size - Male householder": 3.27,
    "Average Household Size - Married-couple family household": 3.24,
    "Average Household Size - Nonfamily household": 1.23,
    "Average Household Size - Overall": 2.51,
    "Households with one or more people under 18 years - Female householder": 0.612,
    "Households with one or more people under 18 years - Male householder": 0.513,
    "Households with one or more people under 18 years - Married-couple family household": 0.419,
    "Households with one or more people under 18 years - Nonfamily household": 0.007,
    "Households with one or more people under 18 years - Overall": 0.295,
    "Households with one or more people 60 years and over - Female householder": 0.303,
    "Households with one or more people 60 years and over - Male householder": 0.314,
    "Households with one or more people 60 years and over - Married-couple family household": 0.397,
    "Households with one or more people 60 years and over - Nonfamily household": 0.445,
    "Households with one or more people 60 years and over - Overall": 0.399,
  },
  {
    State: "Indiana",
    "Female householder": 297834,
    "Male householder": 132999,
    "Married-couple family household": 1265185,
    "Nonfamily household": 957578,
    "Total households Overall": 2653596,
    "Average Household Size - Female householder": 3.32,
    "Average Household Size - Male householder": 3.2,
    "Average Household Size - Married-couple family household": 3.16,
    "Average Household Size - Nonfamily household": 1.25,
    "Average Household Size - Overall": 2.49,
    "Households with one or more people under 18 years - Female householder": 0.663,
    "Households with one or more people under 18 years - Male householder": 0.592,
    "Households with one or more people under 18 years - Married-couple family household": 0.408,
    "Households with one or more people under 18 years - Nonfamily household": 0.01,
    "Households with one or more people under 18 years - Overall": 0.302,
    "Households with one or more people 60 years and over - Female householder": 0.27,
    "Households with one or more people 60 years and over - Male householder": 0.276,
    "Households with one or more people 60 years and over - Married-couple family household": 0.392,
    "Households with one or more people 60 years and over - Nonfamily household": 0.449,
    "Households with one or more people 60 years and over - Overall": 0.393,
  },
  {
    State: "Iowa",
    "Female householder": 117403,
    "Male householder": 55449,
    "Married-couple family household": 630424,
    "Nonfamily household": 486863,
    "Total households Overall": 1290139,
    "Average Household Size - Female householder": 3.24,
    "Average Household Size - Male householder": 3.21,
    "Average Household Size - Married-couple family household": 3.04,
    "Average Household Size - Nonfamily household": 1.26,
    "Average Household Size - Overall": 2.4,
    "Households with one or more people under 18 years - Female householder": 0.698,
    "Households with one or more people under 18 years - Male householder": 0.648,
    "Households with one or more people under 18 years - Married-couple family household": 0.398,
    "Households with one or more people under 18 years - Nonfamily household": 0.008,
    "Households with one or more people under 18 years - Overall": 0.289,
    "Households with one or more people 60 years and over - Female householder": 0.218,
    "Households with one or more people 60 years and over - Male householder": 0.212,
    "Households with one or more people 60 years and over - Married-couple family household": 0.412,
    "Households with one or more people 60 years and over - Nonfamily household": 0.454,
    "Households with one or more people 60 years and over - Overall": 0.402,
  },
  {
    State: "Kansas",
    "Female householder": 111176,
    "Male householder": 50136,
    "Married-couple family household": 571578,
    "Nonfamily household": 415745,
    "Total households Overall": 1148635,
    "Average Household Size - Female householder": 3.32,
    "Average Household Size - Male householder": 3.24,
    "Average Household Size - Married-couple family household": 3.15,
    "Average Household Size - Nonfamily household": 1.24,
    "Average Household Size - Overall": 2.48,
    "Households with one or more people under 18 years - Female householder": 0.679,
    "Households with one or more people under 18 years - Male householder": 0.615,
    "Households with one or more people under 18 years - Married-couple family household": 0.421,
    "Households with one or more people under 18 years - Nonfamily household": 0.008,
    "Households with one or more people under 18 years - Overall": 0.305,
    "Households with one or more people 60 years and over - Female householder": 0.255,
    "Households with one or more people 60 years and over - Male householder": 0.243,
    "Households with one or more people 60 years and over - Married-couple family household": 0.393,
    "Households with one or more people 60 years and over - Nonfamily household": 0.455,
    "Households with one or more people 60 years and over - Overall": 0.395,
  },
  {
    State: "Kentucky",
    "Female householder": 213879,
    "Male householder": 90229,
    "Married-couple family household": 838364,
    "Nonfamily household": 626630,
    "Total households Overall": 1769102,
    "Average Household Size - Female householder": 3.26,
    "Average Household Size - Male householder": 3.16,
    "Average Household Size - Married-couple family household": 3.13,
    "Average Household Size - Nonfamily household": 1.24,
    "Average Household Size - Overall": 2.48,
    "Households with one or more people under 18 years - Female householder": 0.643,
    "Households with one or more people under 18 years - Male householder": 0.58,
    "Households with one or more people under 18 years - Married-couple family household": 0.406,
    "Households with one or more people under 18 years - Nonfamily household": 0.01,
    "Households with one or more people under 18 years - Overall": 0.303,
    "Households with one or more people 60 years and over - Female householder": 0.292,
    "Households with one or more people 60 years and over - Male householder": 0.304,
    "Households with one or more people 60 years and over - Married-couple family household": 0.402,
    "Households with one or more people 60 years and over - Nonfamily household": 0.476,
    "Households with one or more people 60 years and over - Overall": 0.41,
  },
  {
    State: "Louisiana",
    "Female householder": 273659,
    "Male householder": 91127,
    "Married-couple family household": 755959,
    "Nonfamily household": 644519,
    "Total households Overall": 1765264,
    "Average Household Size - Female householder": 3.65,
    "Average Household Size - Male householder": 3.32,
    "Average Household Size - Married-couple family household": 3.21,
    "Average Household Size - Nonfamily household": 1.22,
    "Average Household Size - Overall": 2.56,
    "Households with one or more people under 18 years - Female householder": 0.65,
    "Households with one or more people under 18 years - Male householder": 0.573,
    "Households with one or more people under 18 years - Married-couple family household": 0.407,
    "Households with one or more people under 18 years - Nonfamily household": 0.006,
    "Households with one or more people under 18 years - Overall": 0.307,
    "Households with one or more people 60 years and over - Female householder": 0.295,
    "Households with one or more people 60 years and over - Male householder": 0.307,
    "Households with one or more people 60 years and over - Married-couple family household": 0.409,
    "Households with one or more people 60 years and over - Nonfamily household": 0.462,
    "Households with one or more people 60 years and over - Overall": 0.406,
  },
  {
    State: "Maine",
    "Female householder": 50769,
    "Male householder": 22930,
    "Married-couple family household": 277978,
    "Nonfamily household": 228495,
    "Total households Overall": 580172,
    "Average Household Size - Female householder": 3.14,
    "Average Household Size - Male householder": 3.17,
    "Average Household Size - Married-couple family household": 2.91,
    "Average Household Size - Nonfamily household": 1.27,
    "Average Household Size - Overall": 2.29,
    "Households with one or more people under 18 years - Female householder": 0.625,
    "Households with one or more people under 18 years - Male householder": 0.585,
    "Households with one or more people under 18 years - Married-couple family household": 0.336,
    "Households with one or more people under 18 years - Nonfamily household": 0.01,
    "Households with one or more people under 18 years - Overall": 0.242,
    "Households with one or more people 60 years and over - Female householder": 0.293,
    "Households with one or more people 60 years and over - Male householder": 0.276,
    "Households with one or more people 60 years and over - Married-couple family household": 0.469,
    "Households with one or more people 60 years and over - Nonfamily household": 0.524,
    "Households with one or more people 60 years and over - Overall": 0.468,
  },
  {
    State: "Maryland",
    "Female householder": 319179,
    "Male householder": 112991,
    "Married-couple family household": 1092896,
    "Nonfamily household": 793058,
    "Total households Overall": 2318124,
    "Average Household Size - Female householder": 3.33,
    "Average Household Size - Male householder": 3.3,
    "Average Household Size - Married-couple family household": 3.3,
    "Average Household Size - Nonfamily household": 1.26,
    "Average Household Size - Overall": 2.6,
    "Households with one or more people under 18 years - Female householder": 0.58,
    "Households with one or more people under 18 years - Male householder": 0.539,
    "Households with one or more people under 18 years - Married-couple family household": 0.431,
    "Households with one or more people under 18 years - Nonfamily household": 0.008,
    "Households with one or more people under 18 years - Overall": 0.312,
    "Households with one or more people 60 years and over - Female householder": 0.333,
    "Households with one or more people 60 years and over - Male householder": 0.334,
    "Households with one or more people 60 years and over - Married-couple family household": 0.405,
    "Households with one or more people 60 years and over - Nonfamily household": 0.462,
    "Households with one or more people 60 years and over - Overall": 0.411,
  },
  {
    State: "Massachusetts",
    "Female householder": 321553,
    "Male householder": 124828,
    "Married-couple family household": 1270526,
    "Nonfamily household": 1024088,
    "Total households Overall": 2740995,
    "Average Household Size - Female householder": 3.14,
    "Average Household Size - Male householder": 3.04,
    "Average Household Size - Married-couple family household": 3.17,
    "Average Household Size - Nonfamily household": 1.31,
    "Average Household Size - Overall": 2.46,
    "Households with one or more people under 18 years - Female householder": 0.576,
    "Households with one or more people under 18 years - Male householder": 0.498,
    "Households with one or more people under 18 years - Married-couple family household": 0.414,
    "Households with one or more people under 18 years - Nonfamily household": 0.006,
    "Households with one or more people under 18 years - Overall": 0.285,
    "Households with one or more people 60 years and over - Female householder": 0.322,
    "Households with one or more people 60 years and over - Male householder": 0.338,
    "Households with one or more people 60 years and over - Married-couple family household": 0.42,
    "Households with one or more people 60 years and over - Nonfamily household": 0.459,
    "Households with one or more people 60 years and over - Overall": 0.419,
  },
  {
    State: "Michigan",
    "Female householder": 467630,
    "Male householder": 196199,
    "Married-couple family household": 1864083,
    "Nonfamily household": 1481341,
    "Total households Overall": 4009253,
    "Average Household Size - Female householder": 3.32,
    "Average Household Size - Male householder": 3.17,
    "Average Household Size - Married-couple family household": 3.12,
    "Average Household Size - Nonfamily household": 1.25,
    "Average Household Size - Overall": 2.45,
    "Households with one or more people under 18 years - Female householder": 0.602,
    "Households with one or more people under 18 years - Male householder": 0.54,
    "Households with one or more people under 18 years - Married-couple family household": 0.382,
    "Households with one or more people under 18 years - Nonfamily household": 0.007,
    "Households with one or more people under 18 years - Overall": 0.277,
    "Households with one or more people 60 years and over - Female householder": 0.298,
    "Households with one or more people 60 years and over - Male householder": 0.299,
    "Households with one or more people 60 years and over - Married-couple family household": 0.428,
    "Households with one or more people 60 years and over - Nonfamily household": 0.479,
    "Households with one or more people 60 years and over - Overall": 0.425,
  },
  {
    State: "Minnesota",
    "Female householder": 203070,
    "Male householder": 100888,
    "Married-couple family household": 1120173,
    "Nonfamily household": 831995,
    "Total households Overall": 2256126,
    "Average Household Size - Female householder": 3.31,
    "Average Household Size - Male householder": 3.23,
    "Average Household Size - Married-couple family household": 3.12,
    "Average Household Size - Nonfamily household": 1.29,
    "Average Household Size - Overall": 2.46,
    "Households with one or more people under 18 years - Female householder": 0.667,
    "Households with one or more people under 18 years - Male householder": 0.605,
    "Households with one or more people under 18 years - Married-couple family household": 0.412,
    "Households with one or more people under 18 years - Nonfamily household": 0.008,
    "Households with one or more people under 18 years - Overall": 0.294,
    "Households with one or more people 60 years and over - Female householder": 0.24,
    "Households with one or more people 60 years and over - Male householder": 0.231,
    "Households with one or more people 60 years and over - Married-couple family household": 0.394,
    "Households with one or more people 60 years and over - Nonfamily household": 0.444,
    "Households with one or more people 60 years and over - Overall": 0.391,
  },
  {
    State: "Mississippi",
    "Female householder": 190400,
    "Male householder": 51917,
    "Married-couple family household": 497533,
    "Nonfamily household": 381419,
    "Total households Overall": 1121269,
    "Average Household Size - Female householder": 3.49,
    "Average Household Size - Male householder": 3.27,
    "Average Household Size - Married-couple family household": 3.17,
    "Average Household Size - Nonfamily household": 1.19,
    "Average Household Size - Overall": 2.55,
    "Households with one or more people under 18 years - Female householder": 0.64,
    "Households with one or more people under 18 years - Male householder": 0.53,
    "Households with one or more people under 18 years - Married-couple family household": 0.407,
    "Households with one or more people under 18 years - Nonfamily household": 0.009,
    "Households with one or more people under 18 years - Overall": 0.317,
    "Households with one or more people 60 years and over - Female householder": 0.291,
    "Households with one or more people 60 years and over - Male householder": 0.349,
    "Households with one or more people 60 years and over - Married-couple family household": 0.417,
    "Households with one or more people 60 years and over - Nonfamily household": 0.5,
    "Households with one or more people 60 years and over - Overall": 0.421,
  },
  {
    State: "Missouri",
    "Female householder": 272146,
    "Male householder": 111331,
    "Married-couple family household": 1159320,
    "Nonfamily household": 915527,
    "Total households Overall": 2458324,
    "Average Household Size - Female householder": 3.28,
    "Average Household Size - Male householder": 3.22,
    "Average Household Size - Married-couple family household": 3.11,
    "Average Household Size - Nonfamily household": 1.24,
    "Average Household Size - Overall": 2.44,
    "Households with one or more people under 18 years - Female householder": 0.643,
    "Households with one or more people under 18 years - Male householder": 0.592,
    "Households with one or more people under 18 years - Married-couple family household": 0.396,
    "Households with one or more people under 18 years - Nonfamily household": 0.009,
    "Households with one or more people under 18 years - Overall": 0.288,
    "Households with one or more people 60 years and over - Female householder": 0.28,
    "Households with one or more people 60 years and over - Male householder": 0.28,
    "Households with one or more people 60 years and over - Married-couple family household": 0.409,
    "Households with one or more people 60 years and over - Nonfamily household": 0.463,
    "Households with one or more people 60 years and over - Overall": 0.409,
  },
  {
    State: "Montana",
    "Female householder": 34767,
    "Male householder": 19410,
    "Married-couple family household": 216250,
    "Nonfamily household": 173490,
    "Total households Overall": 443917,
    "Average Household Size - Female householder": 3.45,
    "Average Household Size - Male householder": 3.31,
    "Average Household Size - Married-couple family household": 3.02,
    "Average Household Size - Nonfamily household": 1.3,
    "Average Household Size - Overall": 2.39,
    "Households with one or more people under 18 years - Female householder": 0.654,
    "Households with one or more people under 18 years - Male householder": 0.629,
    "Households with one or more people under 18 years - Married-couple family household": 0.367,
    "Households with one or more people under 18 years - Nonfamily household": 0.008,
    "Households with one or more people under 18 years - Overall": 0.261,
    "Households with one or more people 60 years and over - Female householder": 0.307,
    "Households with one or more people 60 years and over - Male householder": 0.256,
    "Households with one or more people 60 years and over - Married-couple family household": 0.448,
    "Households with one or more people 60 years and over - Nonfamily household": 0.473,
    "Households with one or more people 60 years and over - Overall": 0.438,
  },
  {
    State: "Nebraska",
    "Female householder": 72173,
    "Male householder": 35404,
    "Married-couple family household": 382954,
    "Nonfamily household": 285848,
    "Total households Overall": 776379,
    "Average Household Size - Female householder": 3.29,
    "Average Household Size - Male householder": 3.13,
    "Average Household Size - Married-couple family household": 3.15,
    "Average Household Size - Nonfamily household": 1.25,
    "Average Household Size - Overall": 2.46,
    "Households with one or more people under 18 years - Female householder": 0.699,
    "Households with one or more people under 18 years - Male householder": 0.616,
    "Households with one or more people under 18 years - Married-couple family household": 0.427,
    "Households with one or more people under 18 years - Nonfamily household": 0.01,
    "Households with one or more people under 18 years - Overall": 0.307,
    "Households with one or more people 60 years and over - Female householder": 0.227,
    "Households with one or more people 60 years and over - Male householder": 0.214,
    "Households with one or more people 60 years and over - Married-couple family household": 0.385,
    "Households with one or more people 60 years and over - Nonfamily household": 0.441,
    "Households with one or more people 60 years and over - Overall": 0.383,
  },
  {
    State: "Nevada",
    "Female householder": 150470,
    "Male householder": 77817,
    "Married-couple family household": 514327,
    "Nonfamily household": 421057,
    "Total households Overall": 1163671,
    "Average Household Size - Female householder": 3.59,
    "Average Household Size - Male householder": 3.48,
    "Average Household Size - Married-couple family household": 3.31,
    "Average Household Size - Nonfamily household": 1.32,
    "Average Household Size - Overall": 2.64,
    "Households with one or more people under 18 years - Female householder": 0.622,
    "Households with one or more people under 18 years - Male householder": 0.549,
    "Households with one or more people under 18 years - Married-couple family household": 0.408,
    "Households with one or more people under 18 years - Nonfamily household": 0.009,
    "Households with one or more people under 18 years - Overall": 0.301,
    "Households with one or more people 60 years and over - Female householder": 0.3,
    "Households with one or more people 60 years and over - Male householder": 0.312,
    "Households with one or more people 60 years and over - Married-couple family household": 0.42,
    "Households with one or more people 60 years and over - Nonfamily household": 0.444,
    "Households with one or more people 60 years and over - Overall": 0.406,
  },
  {
    State: "New Hampshire",
    "Female householder": 45996,
    "Male householder": 23864,
    "Married-couple family household": 284046,
    "Nonfamily household": 191210,
    "Total households Overall": 545116,
    "Average Household Size - Female householder": 3.34,
    "Average Household Size - Male householder": 3.28,
    "Average Household Size - Married-couple family household": 3.02,
    "Average Household Size - Nonfamily household": 1.3,
    "Average Household Size - Overall": 2.46,
    "Households with one or more people under 18 years - Female householder": 0.613,
    "Households with one or more people under 18 years - Male householder": 0.561,
    "Households with one or more people under 18 years - Married-couple family household": 0.358,
    "Households with one or more people under 18 years - Nonfamily household": 0.009,
    "Households with one or more people under 18 years - Overall": 0.266,
    "Households with one or more people 60 years and over - Female householder": 0.298,
    "Households with one or more people 60 years and over - Male householder": 0.314,
    "Households with one or more people 60 years and over - Married-couple family household": 0.446,
    "Households with one or more people 60 years and over - Nonfamily household": 0.504,
    "Households with one or more people 60 years and over - Overall": 0.448,
  },
  {
    State: "New Jersey",
    "Female householder": 437620,
    "Male householder": 170278,
    "Married-couple family household": 1732602,
    "Nonfamily household": 1097662,
    "Total households Overall": 3438162,
    "Average Household Size - Female householder": 3.27,
    "Average Household Size - Male householder": 3.18,
    "Average Household Size - Married-couple family household": 3.32,
    "Average Household Size - Nonfamily household": 1.22,
    "Average Household Size - Overall": 2.64,
    "Households with one or more people under 18 years - Female householder": 0.542,
    "Households with one or more people under 18 years - Male householder": 0.485,
    "Households with one or more people under 18 years - Married-couple family household": 0.439,
    "Households with one or more people under 18 years - Nonfamily household": 0.006,
    "Households with one or more people under 18 years - Overall": 0.316,
    "Households with one or more people 60 years and over - Female householder": 0.351,
    "Households with one or more people 60 years and over - Male householder": 0.357,
    "Households with one or more people 60 years and over - Married-couple family household": 0.41,
    "Households with one or more people 60 years and over - Nonfamily household": 0.502,
    "Households with one or more people 60 years and over - Overall": 0.43,
  },
  {
    State: "New Mexico",
    "Female householder": 111782,
    "Male householder": 50363,
    "Married-couple family household": 341009,
    "Nonfamily household": 309698,
    "Total households Overall": 812852,
    "Average Household Size - Female householder": 3.66,
    "Average Household Size - Male householder": 3.53,
    "Average Household Size - Married-couple family household": 3.23,
    "Average Household Size - Nonfamily household": 1.23,
    "Average Household Size - Overall": 2.55,
    "Households with one or more people under 18 years - Female householder": 0.635,
    "Households with one or more people under 18 years - Male householder": 0.602,
    "Households with one or more people under 18 years - Married-couple family household": 0.38,
    "Households with one or more people under 18 years - Nonfamily household": 0.005,
    "Households with one or more people under 18 years - Overall": 0.286,
    "Households with one or more people 60 years and over - Female householder": 0.31,
    "Households with one or more people 60 years and over - Male householder": 0.287,
    "Households with one or more people 60 years and over - Married-couple family household": 0.456,
    "Households with one or more people 60 years and over - Nonfamily household": 0.499,
    "Households with one or more people 60 years and over - Overall": 0.442,
  },
  {
    State: "New York",
    "Female householder": 1049771,
    "Male householder": 385243,
    "Married-couple family household": 3299986,
    "Nonfamily household": 2869523,
    "Total households Overall": 7604523,
    "Average Household Size - Female householder": 3.33,
    "Average Household Size - Male householder": 3.23,
    "Average Household Size - Married-couple family household": 3.34,
    "Average Household Size - Nonfamily household": 1.27,
    "Average Household Size - Overall": 2.55,
    "Households with one or more people under 18 years - Female householder": 0.548,
    "Households with one or more people under 18 years - Male householder": 0.465,
    "Households with one or more people under 18 years - Married-couple family household": 0.418,
    "Households with one or more people under 18 years - Nonfamily household": 0.006,
    "Households with one or more people under 18 years - Overall": 0.283,
    "Households with one or more people 60 years and over - Female householder": 0.365,
    "Households with one or more people 60 years and over - Male householder": 0.386,
    "Households with one or more people 60 years and over - Married-couple family household": 0.428,
    "Households with one or more people 60 years and over - Nonfamily household": 0.466,
    "Households with one or more people 60 years and over - Overall": 0.432,
  },
  {
    State: "North Carolina",
    "Female householder": 519027,
    "Male householder": 181966,
    "Married-couple family household": 1952436,
    "Nonfamily household": 1451803,
    "Total households Overall": 4105232,
    "Average Household Size - Female householder": 3.34,
    "Average Household Size - Male householder": 3.26,
    "Average Household Size - Married-couple family household": 3.1,
    "Average Household Size - Nonfamily household": 1.25,
    "Average Household Size - Overall": 2.48,
    "Households with one or more people under 18 years - Female householder": 0.635,
    "Households with one or more people under 18 years - Male householder": 0.556,
    "Households with one or more people under 18 years - Married-couple family household": 0.398,
    "Households with one or more people under 18 years - Nonfamily household": 0.008,
    "Households with one or more people under 18 years - Overall": 0.297,
    "Households with one or more people 60 years and over - Female householder": 0.284,
    "Households with one or more people 60 years and over - Male householder": 0.292,
    "Households with one or more people 60 years and over - Married-couple family household": 0.406,
    "Households with one or more people 60 years and over - Nonfamily household": 0.453,
    "Households with one or more people 60 years and over - Overall": 0.402,
  },
  {
    State: "North Dakota",
    "Female householder": 24036,
    "Male householder": 12714,
    "Married-couple family household": 151567,
    "Nonfamily household": 131721,
    "Total households Overall": 320038,
    "Average Household Size - Female householder": 3.19,
    "Average Household Size - Male householder": 3.28,
    "Average Household Size - Married-couple family household": 3.08,
    "Average Household Size - Nonfamily household": 1.25,
    "Average Household Size - Overall": 2.34,
    "Households with one or more people under 18 years - Female householder": 0.727,
    "Households with one or more people under 18 years - Male householder": 0.621,
    "Households with one or more people under 18 years - Married-couple family household": 0.416,
    "Households with one or more people under 18 years - Nonfamily household": 0.005,
    "Households with one or more people under 18 years - Overall": 0.278,
    "Households with one or more people 60 years and over - Female householder": 0.186,
    "Households with one or more people 60 years and over - Male householder": 0.176,
    "Households with one or more people 60 years and over - Married-couple family household": 0.379,
    "Households with one or more people 60 years and over - Nonfamily household": 0.383,
    "Households with one or more people 60 years and over - Overall": 0.358,
  },
  {
    State: "Ohio",
    "Female householder": 578040,
    "Male householder": 228367,
    "Married-couple family household": 2154997,
    "Nonfamily household": 1828004,
    "Total households Overall": 4789408,
    "Average Household Size - Female householder": 3.23,
    "Average Household Size - Male householder": 3.14,
    "Average Household Size - Married-couple family household": 3.09,
    "Average Household Size - Nonfamily household": 1.23,
    "Average Household Size - Overall": 2.4,
    "Households with one or more people under 18 years - Female householder": 0.646,
    "Households with one or more people under 18 years - Male householder": 0.585,
    "Households with one or more people under 18 years - Married-couple family household": 0.391,
    "Households with one or more people under 18 years - Nonfamily household": 0.008,
    "Households with one or more people under 18 years - Overall": 0.285,
    "Households with one or more people 60 years and over - Female householder": 0.27,
    "Households with one or more people 60 years and over - Male householder": 0.285,
    "Households with one or more people 60 years and over - Married-couple family household": 0.416,
    "Households with one or more people 60 years and over - Nonfamily household": 0.471,
    "Households with one or more people 60 years and over - Overall": 0.413,
  },
  {
    State: "Oklahoma",
    "Female householder": 182992,
    "Male householder": 79943,
    "Married-couple family household": 724403,
    "Nonfamily household": 535373,
    "Total households Overall": 1522711,
    "Average Household Size - Female householder": 3.37,
    "Average Household Size - Male householder": 3.3,
    "Average Household Size - Married-couple family household": 3.19,
    "Average Household Size - Nonfamily household": 1.24,
    "Average Household Size - Overall": 2.53,
    "Households with one or more people under 18 years - Female householder": 0.661,
    "Households with one or more people under 18 years - Male householder": 0.606,
    "Households with one or more people under 18 years - Married-couple family household": 0.427,
    "Households with one or more people under 18 years - Nonfamily household": 0.009,
    "Households with one or more people under 18 years - Overall": 0.318,
    "Households with one or more people 60 years and over - Female householder": 0.282,
    "Households with one or more people 60 years and over - Male householder": 0.267,
    "Households with one or more people 60 years and over - Married-couple family household": 0.39,
    "Households with one or more people 60 years and over - Nonfamily household": 0.465,
    "Households with one or more people 60 years and over - Overall": 0.397,
  },
  {
    State: "Oregon",
    "Female householder": 166606,
    "Male householder": 79634,
    "Married-couple family household": 796148,
    "Nonfamily household": 638412,
    "Total households Overall": 1680800,
    "Average Household Size - Female householder": 3.24,
    "Average Household Size - Male householder": 3.2,
    "Average Household Size - Married-couple family household": 3.1,
    "Average Household Size - Nonfamily household": 1.37,
    "Average Household Size - Overall": 2.46,
    "Households with one or more people under 18 years - Female householder": 0.607,
    "Households with one or more people under 18 years - Male householder": 0.582,
    "Households with one or more people under 18 years - Married-couple family household": 0.393,
    "Households with one or more people under 18 years - Nonfamily household": 0.008,
    "Households with one or more people under 18 years - Overall": 0.277,
    "Households with one or more people 60 years and over - Female householder": 0.308,
    "Households with one or more people 60 years and over - Male householder": 0.29,
    "Households with one or more people 60 years and over - Married-couple family household": 0.426,
    "Households with one or more people 60 years and over - Nonfamily household": 0.458,
    "Households with one or more people 60 years and over - Overall": 0.42,
  },
  {
    State: "Pennsylvania",
    "Female householder": 604861,
    "Male householder": 241054,
    "Married-couple family household": 2431979,
    "Nonfamily household": 1915833,
    "Total households Overall": 5193727,
    "Average Household Size - Female householder": 3.25,
    "Average Household Size - Male householder": 3.11,
    "Average Household Size - Married-couple family household": 3.08,
    "Average Household Size - Nonfamily household": 1.23,
    "Average Household Size - Overall": 2.42,
    "Households with one or more people under 18 years - Female householder": 0.603,
    "Households with one or more people under 18 years - Male householder": 0.544,
    "Households with one or more people under 18 years - Married-couple family household": 0.379,
    "Households with one or more people under 18 years - Nonfamily household": 0.006,
    "Households with one or more people under 18 years - Overall": 0.275,
    "Households with one or more people 60 years and over - Female householder": 0.321,
    "Households with one or more people 60 years and over - Male householder": 0.328,
    "Households with one or more people 60 years and over - Married-couple family household": 0.436,
    "Households with one or more people 60 years and over - Nonfamily household": 0.494,
    "Households with one or more people 60 years and over - Overall": 0.439,
  },
  {
    State: "Puerto Rico",
    "Female householder": 274304,
    "Male householder": 81633,
    "Married-couple family household": 440016,
    "Nonfamily household": 423705,
    "Total households Overall": 1219658,
    "Average Household Size - Female householder": 3.58,
    "Average Household Size - Male householder": 3.79,
    "Average Household Size - Married-couple family household": 3.3,
    "Average Household Size - Nonfamily household": 1.17,
    "Average Household Size - Overall": 2.65,
    "Households with one or more people under 18 years - Female householder": 0.52,
    "Households with one or more people under 18 years - Male householder": 0.485,
    "Households with one or more people under 18 years - Married-couple family household": 0.284,
    "Households with one or more people under 18 years - Nonfamily household": 0.002,
    "Households with one or more people under 18 years - Overall": 0.253,
    "Households with one or more people 60 years and over - Female householder": 0.369,
    "Households with one or more people 60 years and over - Male householder": 0.41,
    "Households with one or more people 60 years and over - Married-couple family household": 0.551,
    "Households with one or more people 60 years and over - Nonfamily household": 0.595,
    "Households with one or more people 60 years and over - Overall": 0.516,
  },
  {
    State: "Rhode Island",
    "Female householder": 54649,
    "Male householder": 22355,
    "Married-couple family household": 188597,
    "Nonfamily household": 166618,
    "Total households Overall": 432219,
    "Average Household Size - Female householder": 3.21,
    "Average Household Size - Male householder": 3.11,
    "Average Household Size - Married-couple family household": 3.15,
    "Average Household Size - Nonfamily household": 1.26,
    "Average Household Size - Overall": 2.43,
    "Households with one or more people under 18 years - Female householder": 0.595,
    "Households with one or more people under 18 years - Male householder": 0.526,
    "Households with one or more people under 18 years - Married-couple family household": 0.385,
    "Households with one or more people under 18 years - Nonfamily household": 0.007,
    "Households with one or more people under 18 years - Overall": 0.273,
    "Households with one or more people 60 years and over - Female householder": 0.301,
    "Households with one or more people 60 years and over - Male householder": 0.323,
    "Households with one or more people 60 years and over - Married-couple family household": 0.44,
    "Households with one or more people 60 years and over - Nonfamily household": 0.487,
    "Households with one or more people 60 years and over - Overall": 0.434,
  },
  {
    State: "South Carolina",
    "Female householder": 275800,
    "Male householder": 90565,
    "Married-couple family household": 951952,
    "Nonfamily household": 704768,
    "Total households Overall": 2023085,
    "Average Household Size - Female householder": 3.41,
    "Average Household Size - Male householder": 3.17,
    "Average Household Size - Married-couple family household": 3.05,
    "Average Household Size - Nonfamily household": 1.23,
    "Average Household Size - Overall": 2.47,
    "Households with one or more people under 18 years - Female householder": 0.626,
    "Households with one or more people under 18 years - Male householder": 0.512,
    "Households with one or more people under 18 years - Married-couple family household": 0.374,
    "Households with one or more people under 18 years - Nonfamily household": 0.008,
    "Households with one or more people under 18 years - Overall": 0.287,
    "Households with one or more people 60 years and over - Female householder": 0.313,
    "Households with one or more people 60 years and over - Male householder": 0.31,
    "Households with one or more people 60 years and over - Married-couple family household": 0.441,
    "Households with one or more people 60 years and over - Nonfamily household": 0.477,
    "Households with one or more people 60 years and over - Overall": 0.43,
  },
  {
    State: "South Dakota",
    "Female householder": 29737,
    "Male householder": 16235,
    "Married-couple family household": 172549,
    "Nonfamily household": 132661,
    "Total households Overall": 351182,
    "Average Household Size - Female householder": 3.6,
    "Average Household Size - Male householder": 3.32,
    "Average Household Size - Married-couple family household": 3.08,
    "Average Household Size - Nonfamily household": 1.25,
    "Average Household Size - Overall": 2.44,
    "Households with one or more people under 18 years - Female householder": 0.722,
    "Households with one or more people under 18 years - Male householder": 0.639,
    "Households with one or more people under 18 years - Married-couple family household": 0.406,
    "Households with one or more people under 18 years - Nonfamily household": 0.011,
    "Households with one or more people under 18 years - Overall": 0.294,
    "Households with one or more people 60 years and over - Female householder": 0.236,
    "Households with one or more people 60 years and over - Male householder": 0.248,
    "Households with one or more people 60 years and over - Married-couple family household": 0.41,
    "Households with one or more people 60 years and over - Nonfamily household": 0.452,
    "Households with one or more people 60 years and over - Overall": 0.403,
  },
  {
    State: "Tennessee",
    "Female householder": 342263,
    "Male householder": 129004,
    "Married-couple family household": 1287744,
    "Nonfamily household": 954624,
    "Total households Overall": 2713635,
    "Average Household Size - Female householder": 3.34,
    "Average Household Size - Male householder": 3.24,
    "Average Household Size - Married-couple family household": 3.12,
    "Average Household Size - Nonfamily household": 1.25,
    "Average Household Size - Overall": 2.5,
    "Households with one or more people under 18 years - Female householder": 0.635,
    "Households with one or more people under 18 years - Male householder": 0.564,
    "Households with one or more people under 18 years - Married-couple family household": 0.396,
    "Households with one or more people under 18 years - Nonfamily household": 0.009,
    "Households with one or more people under 18 years - Overall": 0.298,
    "Households with one or more people 60 years and over - Female householder": 0.304,
    "Households with one or more people 60 years and over - Male householder": 0.302,
    "Households with one or more people 60 years and over - Married-couple family household": 0.402,
    "Households with one or more people 60 years and over - Nonfamily household": 0.455,
    "Households with one or more people 60 years and over - Overall": 0.403,
  },
  {
    State: "Texas",
    "Female householder": 1420225,
    "Male householder": 553575,
    "Married-couple family household": 5200043,
    "Nonfamily household": 3316710,
    "Total households Overall": 10490553,
    "Average Household Size - Female householder": 3.5,
    "Average Household Size - Male householder": 3.31,
    "Average Household Size - Married-couple family household": 3.4,
    "Average Household Size - Nonfamily household": 1.25,
    "Average Household Size - Overall": 2.73,
    "Households with one or more people under 18 years - Female householder": 0.652,
    "Households with one or more people under 18 years - Male householder": 0.552,
    "Households with one or more people under 18 years - Married-couple family household": 0.477,
    "Households with one or more people under 18 years - Nonfamily household": 0.007,
    "Households with one or more people under 18 years - Overall": 0.356,
    "Households with one or more people 60 years and over - Female householder": 0.28,
    "Households with one or more people 60 years and over - Male householder": 0.286,
    "Households with one or more people 60 years and over - Married-couple family household": 0.351,
    "Households with one or more people 60 years and over - Nonfamily household": 0.386,
    "Households with one or more people 60 years and over - Overall": 0.349,
  },
  {
    State: "Utah",
    "Female householder": 93858,
    "Male householder": 49243,
    "Married-couple family household": 639567,
    "Nonfamily household": 280151,
    "Total households Overall": 1062819,
    "Average Household Size - Female householder": 3.56,
    "Average Household Size - Male householder": 3.37,
    "Average Household Size - Married-couple family household": 3.65,
    "Average Household Size - Nonfamily household": 1.41,
    "Average Household Size - Overall": 3.04,
    "Households with one or more people under 18 years - Female householder": 0.624,
    "Households with one or more people under 18 years - Male householder": 0.568,
    "Households with one or more people under 18 years - Married-couple family household": 0.512,
    "Households with one or more people under 18 years - Nonfamily household": 0.009,
    "Households with one or more people under 18 years - Overall": 0.392,
    "Households with one or more people 60 years and over - Female householder": 0.291,
    "Households with one or more people 60 years and over - Male householder": 0.233,
    "Households with one or more people 60 years and over - Married-couple family household": 0.313,
    "Households with one or more people 60 years and over - Nonfamily household": 0.392,
    "Households with one or more people 60 years and over - Overall": 0.328,
  },
  {
    State: "Vermont",
    "Female householder": 22199,
    "Male householder": 10663,
    "Married-couple family household": 124656,
    "Nonfamily household": 108340,
    "Total households Overall": 265858,
    "Average Household Size - Female householder": 3.27,
    "Average Household Size - Male householder": 3.32,
    "Average Household Size - Married-couple family household": 2.95,
    "Average Household Size - Nonfamily household": 1.32,
    "Average Household Size - Overall": 2.33,
    "Households with one or more people under 18 years - Female householder": 0.647,
    "Households with one or more people under 18 years - Male householder": 0.62,
    "Households with one or more people under 18 years - Married-couple family household": 0.339,
    "Households with one or more people under 18 years - Nonfamily household": 0.006,
    "Households with one or more people under 18 years - Overall": 0.241,
    "Households with one or more people 60 years and over - Female householder": 0.276,
    "Households with one or more people 60 years and over - Male householder": 0.267,
    "Households with one or more people 60 years and over - Married-couple family household": 0.468,
    "Households with one or more people 60 years and over - Nonfamily household": 0.509,
    "Households with one or more people 60 years and over - Overall": 0.46,
  },
  {
    State: "Virginia",
    "Female householder": 376557,
    "Male householder": 147751,
    "Married-couple family household": 1624155,
    "Nonfamily household": 1141313,
    "Total households Overall": 3289776,
    "Average Household Size - Female householder": 3.33,
    "Average Household Size - Male householder": 3.23,
    "Average Household Size - Married-couple family household": 3.2,
    "Average Household Size - Nonfamily household": 1.28,
    "Average Household Size - Overall": 2.55,
    "Households with one or more people under 18 years - Female householder": 0.611,
    "Households with one or more people under 18 years - Male householder": 0.534,
    "Households with one or more people under 18 years - Married-couple family household": 0.427,
    "Households with one or more people under 18 years - Nonfamily household": 0.008,
    "Households with one or more people under 18 years - Overall": 0.307,
    "Households with one or more people 60 years and over - Female householder": 0.313,
    "Households with one or more people 60 years and over - Male householder": 0.321,
    "Households with one or more people 60 years and over - Married-couple family household": 0.393,
    "Households with one or more people 60 years and over - Nonfamily household": 0.446,
    "Households with one or more people 60 years and over - Overall": 0.399,
  },
  {
    State: "Washington",
    "Female householder": 286992,
    "Male householder": 141548,
    "Married-couple family household": 1482230,
    "Nonfamily household": 1068502,
    "Total households Overall": 2979272,
    "Average Household Size - Female householder": 3.32,
    "Average Household Size - Male householder": 3.26,
    "Average Household Size - Married-couple family household": 3.16,
    "Average Household Size - Nonfamily household": 1.34,
    "Average Household Size - Overall": 2.53,
    "Households with one or more people under 18 years - Female householder": 0.625,
    "Households with one or more people under 18 years - Male householder": 0.579,
    "Households with one or more people under 18 years - Married-couple family household": 0.421,
    "Households with one or more people under 18 years - Nonfamily household": 0.009,
    "Households with one or more people under 18 years - Overall": 0.3,
    "Households with one or more people 60 years and over - Female householder": 0.292,
    "Households with one or more people 60 years and over - Male householder": 0.277,
    "Households with one or more people 60 years and over - Married-couple family household": 0.39,
    "Households with one or more people 60 years and over - Nonfamily household": 0.423,
    "Households with one or more people 60 years and over - Overall": 0.387,
  },
  {
    State: "West Virginia",
    "Female householder": 76505,
    "Male householder": 34549,
    "Married-couple family household": 338650,
    "Nonfamily household": 266336,
    "Total households Overall": 716040,
    "Average Household Size - Female householder": 3.42,
    "Average Household Size - Male householder": 3.39,
    "Average Household Size - Married-couple family household": 3.06,
    "Average Household Size - Nonfamily household": 1.22,
    "Average Household Size - Overall": 2.43,
    "Households with one or more people under 18 years - Female householder": 0.604,
    "Households with one or more people under 18 years - Male householder": 0.528,
    "Households with one or more people under 18 years - Married-couple family household": 0.355,
    "Households with one or more people under 18 years - Nonfamily household": 0.007,
    "Households with one or more people under 18 years - Overall": 0.26,
    "Households with one or more people 60 years and over - Female householder": 0.354,
    "Households with one or more people 60 years and over - Male householder": 0.353,
    "Households with one or more people 60 years and over - Married-couple family household": 0.467,
    "Households with one or more people 60 years and over - Nonfamily household": 0.528,
    "Households with one or more people 60 years and over - Overall": 0.472,
  },
  {
    State: "Wisconsin",
    "Female householder": 225419,
    "Male householder": 110094,
    "Married-couple family household": 1152787,
    "Nonfamily household": 937188,
    "Total households Overall": 2425488,
    "Average Household Size - Female householder": 3.22,
    "Average Household Size - Male householder": 3.16,
    "Average Household Size - Married-couple family household": 3.02,
    "Average Household Size - Nonfamily household": 1.27,
    "Average Household Size - Overall": 2.37,
    "Households with one or more people under 18 years - Female householder": 0.665,
    "Households with one or more people under 18 years - Male householder": 0.618,
    "Households with one or more people under 18 years - Married-couple family household": 0.372,
    "Households with one or more people under 18 years - Nonfamily household": 0.008,
    "Households with one or more people under 18 years - Overall": 0.27,
    "Households with one or more people 60 years and over - Female householder": 0.235,
    "Households with one or more people 60 years and over - Male householder": 0.236,
    "Households with one or more people 60 years and over - Married-couple family household": 0.424,
    "Households with one or more people 60 years and over - Nonfamily household": 0.452,
    "Households with one or more people 60 years and over - Overall": 0.409,
  },
  {
    State: "Wyoming",
    "Female householder": 18247,
    "Male householder": 10467,
    "Married-couple family household": 118766,
    "Nonfamily household": 86676,
    "Total households Overall": 234156,
    "Average Household Size - Female householder": 3.32,
    "Average Household Size - Male householder": 3.06,
    "Average Household Size - Married-couple family household": 3.07,
    "Average Household Size - Nonfamily household": 1.24,
    "Average Household Size - Overall": 2.41,
    "Households with one or more people under 18 years - Female householder": 0.699,
    "Households with one or more people under 18 years - Male householder": 0.589,
    "Households with one or more people under 18 years - Married-couple family household": 0.403,
    "Households with one or more people under 18 years - Nonfamily household": 0.009,
    "Households with one or more people under 18 years - Overall": 0.289,
    "Households with one or more people 60 years and over - Female householder": 0.236,
    "Households with one or more people 60 years and over - Male householder": 0.26,
    "Households with one or more people 60 years and over - Married-couple family household": 0.403,
    "Households with one or more people 60 years and over - Nonfamily household": 0.469,
    "Households with one or more people 60 years and over - Overall": 0.408,
  },
  {
    State: "Total",
    "Female householder": null,
    "Male householder": null,
    "Married-couple family household": null,
    "Nonfamily household": null,
    "Total households Overall": null,
    "Average Household Size - Female householder": 176.34,
    "Average Household Size - Male householder": 169.99,
    "Average Household Size - Married-couple family household": 165.05,
    "Average Household Size - Nonfamily household": 65.91,
    "Average Household Size - Overall": 130.79,
    "Households with one or more people under 18 years - Female householder": 32.689,
    "Households with one or more people under 18 years - Male householder": 29.227,
    "Households with one or more people under 18 years - Married-couple family household": 20.903,
    "Households with one or more people under 18 years - Nonfamily household": 0.397,
    "Households with one or more people under 18 years - Overall": 15.226,
    "Households with one or more people 60 years and over - Female householder": 15.487,
    "Households with one or more people 60 years and over - Male householder": 15.538,
    "Households with one or more people 60 years and over - Married-couple family household": 21.593,
    "Households with one or more people 60 years and over - Nonfamily household": 24.051,
    "Households with one or more people 60 years and over - Overall": 21.471,
  },
];
